# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-28 13:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='modules',
            name='date',
            field=models.CharField(choices=[('1 november 2016', '1 november 2016'), ('1 februari 2016', '1 februari 2016'), ('1 april 2016', '1 april 2016')], default='1 november 2016', max_length=35),
        ),
    ]
