# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-29 12:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20160829_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modules',
            name='date',
            field=models.CharField(choices=[('---', '---'), ('1 november 2016', '1 november 2016'), ('1 februari 2016', '1 februari 2016'), ('1 april 2016', '1 april 2016')], default='---', max_length=35),
        ),
    ]
