# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-29 18:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_modules_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modules',
            name='location',
        ),
    ]
