# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-29 12:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_modules_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modules',
            name='buy_module',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Module kopen'),
        ),
    ]
