# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-29 14:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20160829_1242'),
    ]

    operations = [
        migrations.AddField(
            model_name='modules',
            name='location',
            field=models.CharField(blank=True, choices=[('Food Court', 'Food Court'), ('KFC', 'KFC')], max_length=25),
        ),
    ]
