# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-29 19:02
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_modules_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='modules',
            name='date1',
            field=models.DateTimeField(default=datetime.datetime(2016, 7, 1, 0, 0)),
        ),
        migrations.AddField(
            model_name='modules',
            name='date2',
            field=models.DateTimeField(default=datetime.datetime(2016, 2, 1, 0, 0)),
        ),
    ]
